### ISSUE TITLE
'numpy.flatiter' object has no attribute 'tolist'

### ISSUE THREAD

**Issue by mone20chss** [fangohr/ovf2vtk#3]
Hi. Im running the programm winovf2vtk.py and it almost work, but at the last line it post this error: "AttributeError: 'numpy.flatiter' object has no attribute 'tolist'" instead of show the message "saving file (namefile.vtk)". The complete message is in the link: https://user-images.githubusercontent.com/64573135/80873136-1424a280-8c7c-11ea-8d38-4afb6faf32f1.png

Please helpe me with this errror,  I think that the problem is that in the program winovf2vtk.py, there is no obs variable defined, but I'm not sure.

**Comment by fangohr** [comment]
I don't know, but I recommend you use the more recent `discretisedfield` packages for the conversion functionality: https://discretisedfield.readthedocs.io/en/latest/ipynb/12-tutorial-ovf2vtk.html
